export class CreateCaseDiaryModel {
    _id: string = "";
    registrationDate: string = "";
    applicantName: string = "";
    courtName: string = "";
    respondentName: string = "";
    caseNumber: Number = 0;
    caseName: String = "";
    nextHearingDate: string = "";
    caseStage: string = "";
    applicationType: string = "";
    city: string = "";
    applicationSection: string = "";
    lawyreasonForAbsent: string = "";
    representing: string = "";
    FIRNumber: string = "";
    FIRDate: string = "";
    sectionIPC: string = "";
}
